### ISSUE TITLE
Can't make new post in posts folder

### ISSUE THREAD

**Issue by BoltonBailey** [willofindie/vscode-gohugo#2]
When I run "GoHugo: Create New Content" from the command palette, I enter the filename `posts/test.md`, but the file is created in the content folder rather than the posts subfolder. Also, there is no .md file extension on the created file.

**Comment by BoltonBailey** [comment]
I found a workaround for this, which was to copy my default template into a template specifically for posts. Still, it would be nice to have this fixed.

**Comment by phoenisx** [comment]
Hi @BoltonBailey 
Thanks for using this plugin.

I recently released support for `archetypes` - https://github.com/willofindie/vscode-gohugo/releases/tag/v0.1.0,
which expects defined archetypes templates beforehand, due to which this issue is caused.
I will add support for this in the next release.

**Comment by phoenisx** [comment]
Re-Opening!! Once fixed will close this issue
